Fix `AttributeError: 'tuple' object has no attribute 'size'` issue
I think I found a fix to this issue, although I'm now running into
`OverflowError`s.  You'll probably have to do a bit of investigating
into what you'll have to change in your `model_rnn/*.py` files to make
this work like the LSTM.  I have no experience with either one so I
can't immediately say.

Here's how I tracked down this particular issue:
 - I noticed that we were getting `AttributeError`s when running
   `RNNBase::check_forward_args`. Specifically, they were being thrown
   on line 156 of `nn/modules/rnn.py`, as reported by the Python
   runtime.
 - I tried running the original `model_lstm`, and noticed that we
   successfully made it past this function call (by stepping through
   with the debugger). Thus, the problem must be in how we're passing
   our parameters to `check_forward_args`.
 - Also using the debugger, I was able to figure out that both we and
   the LSTM model were passing identical inputs to `check_forward_args`
   by running them both at the same time in side-by-side debuggers (i.e.
   two terminals).
 - I realized that `hidden` in our case was a tuple, not a torch.Tensor
   (the things that generally have a `.size` attribute).  However, I
   noticed on line 151 just above it, if our `mode` was "LSTM", then
   we would call `check_hidden_size` on `hidden[0]` and `hidden[1]`
   (recall `hidden` was a tuple of tensors, so each of `hidden[0]` and
   `hidden[1]` was a tensor, so they both had a `.size` attribute).
 - Based on this observation, I concluded that we were probably just
   initializing our `hidden` tensor incorrectly, so I looked where in
   our code we were initializing that tensor.
 - And, lo and behold, we were explicitly initializing it as a tuple
   in `model_rnn/model.py` line 92 (since we had just directly
   substitued the `if (...) == 'LSTM'` for `if (...) == 'RNN_RELU'`
   without actually checking what that would do :^)

Thus, the only fix that was needed was to use the other constructor for
our hidden tensor (the one like 2 lines below).